" no vi compat
" setlocal foldmethod=indent

set nocompatible
filetype off
" initialize vundle
set rtp+=~/.config/nvim/bundle/Vundle.vim
call vundle#begin('~/.config/nvim/bundle')

Plugin 'VundleVim/Vundle.vim'
Plugin 'itchyny/lightline.vim'
"Plugin 'vim-templates'
Plugin 'davidhalter/jedi-vim'
"Plugin 'SirVer/ultisnips'
Plugin 'https://github.com/takac/vim-hardtime.git'
Plugin 'surround.vim'
Plugin 'ctrlp.vim'
Plugin 'fugitive.vim'

"Language Server
Plugin 'https://github.com/autozimu/LanguageClient-neovim.git'

"Additional colour schemes
Plugin 'https://github.com/rafi/awesome-vim-colorschemes.git'

call vundle#end()
filetype plugin indent on

"lightline fix
set laststatus=2

" Customize the settings for vim-template plugin
let g:email = "jeremy.minton@eigentech.com"
let g:user = "jeremy-minton"
let g:fdocstr = "function docstring (to change)"
let g:cdocstr = "class docstring (to change)"

" Ctrlp config
let g:ctrlp_working_path_mode = 'r'

" Hardmode config
let g:hardtime_default_on = 0

" fugitive.vim config
set diffopt+=vertical
cabbrev q qa
cabbrev x xa
command! W w

source ~/dotfiles/vimrc/vimrc_colors
source ~/dotfiles/vimrc/vimrc_tabs
source ~/dotfiles/vimrc/vimrc_arrows
source ~/dotfiles/vimrc/vimrc_beeps
source ~/dotfiles/vimrc/vimrc_numbering
"source ~/dotfiles/vimrc/vimrc_spell
source ~/dotfiles/vimrc/vimrc_netrw "replacement for NERDTree
source ~/dotfiles/vimrc/vimrc_search
source ~/dotfiles/vimrc/vimrc_language_server
autocmd BufEnter *.py source ~/dotfiles/vimrc/vimrc_dotpy
source ~/dotfiles/vimrc/vimrc_dotjs
source ~/dotfiles/vimrc/vimrc_todo
